# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
before_install:
#  - ./radiance-build.sh
  - wget http://www.radiance-online.org/download-install/radiance-source-code/latest-release/latest-release/rad5R0all.tar.gz
  - tar xzf rad5R0all.tar.gz
  - pwd
  - ls -l
  - ls -l ray
  - cd ray
  - cp ../makeall-modified makeall
  - sudo ./makeall install
#  - pwd
#  - ../radiance-build.sh
#  - cd ray && ../radiance-build.sh
#  - ../radiance-build.sh
#  - cd ..
#  - sed --in-place '/more License.txt/d' makeall
#  - echo "\ny\n" | sudo ./installib
#  - echo "\n\ny\n2\n\nn\n" | sudo ./makeall install
#  - wget https://github.com/NREL/Radiance/archive/5.0.tar.gz
#  - tar xvf 5.0.tar.gz
#  - mkdir Radiance-5.0/build
#  - cd Radiance-5.0/build && cmake .. && make
#  - sudo make install
#  - sudo apt-get -qq update
#  - sudo apt-get install -y radiance
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make && make test ARGS="-V"
